version: '3.3'

services:
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - "80:80"
    depends_on:
      - web
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn --workers=4 yandex_dzen.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
    expose:
      - "8000"
    env_file:
      - ./.env.prod
    depends_on:
      - db
  celery:
    build: ./app
    command: celery -A yandex_dzen worker -l INFO
    volumes:
      - static_volume:/home/app/
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
  db:
    image: postgres:15.1
    ports:
      - "5432:5456"
    volumes:
      - postgres_data:/var/lib/postgres/data/
    env_file:
      - ./.env.prod.db
  redis:
    image: redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
  static_volume: